name:                 my-interpreter
version:              0.1.0.0
visibility:           public
id:                   my-interpreter-0.1.0.0-F7fYAaFw4rNDruacdQbZrX
key:                  my-interpreter-0.1.0.0-F7fYAaFw4rNDruacdQbZrX
license:              BSD-3-Clause
abi:                  9b3e9e7253fb4f978dff9cacb1b3f877
exposed:              True
exposed-modules:      Lexer Main Parser Syntax Tokens Types
hidden-modules:       Paths_my_interpreter
import-dirs:
    C:\Users\Anghelo\my-interpreter\.stack-work\install\3d8d5524\lib\x86_64-windows-ghc-9.10.3-b42a\my-interpreter-0.1.0.0-F7fYAaFw4rNDruacdQbZrX

library-dirs:
    C:\Users\Anghelo\my-interpreter\.stack-work\install\3d8d5524\lib\x86_64-windows-ghc-9.10.3-b42a\my-interpreter-0.1.0.0-F7fYAaFw4rNDruacdQbZrX
    C:\Users\Anghelo\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\lib
    C:\Users\Anghelo\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\bin

library-dirs-static:
    C:\Users\Anghelo\my-interpreter\.stack-work\install\3d8d5524\lib\x86_64-windows-ghc-9.10.3-b42a\my-interpreter-0.1.0.0-F7fYAaFw4rNDruacdQbZrX
    C:\Users\Anghelo\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\lib
    C:\Users\Anghelo\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\bin

dynamic-library-dirs:
    C:\Users\Anghelo\my-interpreter\.stack-work\install\3d8d5524\lib\x86_64-windows-ghc-9.10.3-b42a
    C:\Users\Anghelo\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\lib
    C:\Users\Anghelo\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\bin

data-dir:
    C:\Users\Anghelo\my-interpreter\.stack-work\install\3d8d5524\share\x86_64-windows-ghc-9.10.3-b42a\my-interpreter-0.1.0.0

hs-libraries:         HSmy-interpreter-0.1.0.0-F7fYAaFw4rNDruacdQbZrX
include-dirs:
    C:\Users\Anghelo\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\include

depends:
    array-0.5.8.0-8f57 base-4.20.2.0-39f9 containers-0.7-c2a5

haddock-interfaces:
    C:\Users\Anghelo\my-interpreter\.stack-work\install\3d8d5524\doc\my-interpreter-0.1.0.0\my-interpreter.haddock

haddock-html:
    C:\Users\Anghelo\my-interpreter\.stack-work\install\3d8d5524\doc\my-interpreter-0.1.0.0
